# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=32)),
                ('value', models.FloatField()),
                ('week', models.IntegerField()),
            ],
        ),
    ]
