# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-week']},
        ),
        migrations.AddField(
            model_name='sale',
            name='week_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inputs.Week'),
            preserve_default=False,
        ),
    ]
