# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_auto_20180519_0722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hour',
            new_name='Resource',
        ),
    ]
