# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_auto_20180519_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-week']},
        ),
        migrations.AddField(
            model_name='resource',
            name='week_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inputs.Week'),
            preserve_default=False,
        ),
    ]
